"use client";

import { useEffect, useRef, useState } from "react";
import { Sparkles } from "lucide-react";
import { toast } from "sonner";
import { GrammarPointPicker } from "@/components/content/grammar-point-picker";
import { DifficultyLevelPicker } from "@/components/dialogue/difficulty-level-picker";
import { FormalityLevelPicker } from "@/components/dialogue/formality-level-picker";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { dialogueApi } from "@/lib/dialogue/client";
import {
  dialogueLinesFromGenerated,
  generationBriefFromSetting,
} from "@/lib/dialogue/generated-lines";
import {
  formatDialogueTranscriptLine,
  isSpokenLine,
  type DialogueLine,
  type GeneratedLines,
} from "@/lib/dialogue/types";
import type { DialogueDifficulty } from "@/lib/dialogue/difficulty";
import type { DialogueFormality } from "@/lib/dialogue/formality";

const VARIANT_COUNT = 3;

type DialogueVariant = {
  index: number;
  generated: GeneratedLines | null;
  error: string | null;
  loading: boolean;
  compare?: boolean;
};

export function GenerateLinesPanel({
  existingLines,
  collectionId,
  setting,
  menuTitle,
  grammarPointIds,
  onInsert,
  autoGenerateOnMount = false,
  triggerGenerateCount = 0,
}: {
  existingLines: DialogueLine[];
  collectionId?: string;
  setting: string;
  menuTitle?: string;
  grammarPointIds: string[];
  onInsert: (
    lines: DialogueLine[],
    mode: "replace" | "append",
    options?: { setting?: string; grammarPointIds?: string[] }
  ) => void;
  autoGenerateOnMount?: boolean;
  triggerGenerateCount?: number;
}) {
  const defaultSpeakers = [
    ...new Set(
      existingLines.filter(isSpokenLine).map((line) => line.speaker).filter(Boolean),
    ),
  ].slice(0, 2);

  const [extraInstructions, setExtraInstructions] = useState("");
  const [selectedGrammarPointIds, setSelectedGrammarPointIds] =
    useState(grammarPointIds);
  const [speaker1, setSpeaker1] = useState(defaultSpeakers[0] ?? "");
  const [speaker2, setSpeaker2] = useState(defaultSpeakers[1] ?? "");
  const [difficulty, setDifficulty] = useState<DialogueDifficulty>("beginner");
  const [formality, setFormality] = useState<DialogueFormality>("polite");
  const [mode, setMode] = useState<"replace" | "append">(
    existingLines.length > 0 ? "append" : "replace"
  );
  const [variants, setVariants] = useState<DialogueVariant[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const hasAutoGenerated = useRef(false);
  const lastTriggeredGenerate = useRef(0);

  useEffect(() => {
    setSelectedGrammarPointIds(grammarPointIds);
  }, [grammarPointIds]);

  const effectiveBrief = [
    generationBriefFromSetting(setting, menuTitle),
    extraInstructions.trim(),
  ]
    .filter(Boolean)
    .join("\n\n");

  const canGenerate = effectiveBrief.length > 0;

  function insertGenerated(
    generated: GeneratedLines,
    successMessage?: string
  ) {
    const lines = dialogueLinesFromGenerated(
      generated,
      selectedGrammarPointIds
    );
    onInsert(lines, mode, {
      setting: generated.setting ?? (setting.trim() || undefined),
      grammarPointIds:
        selectedGrammarPointIds.length > 0
          ? selectedGrammarPointIds
          : undefined,
    });
    toast.success(
      successMessage ??
        (mode === "replace"
          ? "Draft lines replaced. Review and Save to persist."
          : "Lines appended to draft. Review and Save to persist.")
    );
  }

  async function generateVariants(options?: { autoInsertFirst?: boolean }) {
    if (!canGenerate) return null;

    setIsGenerating(true);
    setVariants(
      Array.from({ length: VARIANT_COUNT }, (_, index) => ({
        index,
        generated: null,
        error: null,
        loading: true,
      }))
    );

    const speakerNames = [speaker1.trim(), speaker2.trim()].filter(Boolean);
    const baseRequest = {
      prompt: effectiveBrief,
      collectionId,
      setting: setting.trim() || undefined,
      speakerNames: speakerNames.length > 0 ? speakerNames : undefined,
      grammarPointIds:
        selectedGrammarPointIds.length > 0
          ? selectedGrammarPointIds
          : undefined,
      existingLines: mode === "append" ? existingLines : undefined,
      mode,
      variantCount: VARIANT_COUNT,
      difficulty,
      formality,
    };

    const results = await Promise.all(
      Array.from({ length: VARIANT_COUNT }, (_, variantIndex) =>
        dialogueApi
          .generateLines({
            ...baseRequest,
            variantIndex,
          })
          .then(({ generated }) => ({
            index: variantIndex,
            generated,
            error: null,
            loading: false,
          }))
          .catch((error: Error) => ({
            index: variantIndex,
            generated: null,
            error: error.message,
            loading: false,
          }))
      )
    );

    setVariants(results);
    setIsGenerating(false);

    const firstSuccess = results.find((result) => result.generated);
    const successCount = results.filter((result) => result.generated).length;

    if (successCount === 0) {
      toast.error("All dialogue generations failed.");
      return null;
    }

    if (successCount < VARIANT_COUNT) {
      toast.warning(
        `Generated ${successCount} of ${VARIANT_COUNT} options. Review the cards below.`
      );
    }

    if (options?.autoInsertFirst && firstSuccess?.generated) {
      insertGenerated(
        firstSuccess.generated,
        "Dialogue generated from setting. Review and Save to persist."
      );
      return firstSuccess.generated;
    }

    return firstSuccess?.generated ?? null;
  }

  useEffect(() => {
    if (
      !autoGenerateOnMount ||
      hasAutoGenerated.current ||
      existingLines.length > 0 ||
      !canGenerate ||
      isGenerating
    ) {
      return;
    }

    hasAutoGenerated.current = true;
    void generateVariants({ autoInsertFirst: true });
  }, [autoGenerateOnMount, canGenerate, existingLines.length, isGenerating]);

  useEffect(() => {
    if (
      triggerGenerateCount <= lastTriggeredGenerate.current ||
      !canGenerate ||
      isGenerating
    ) {
      return;
    }

    lastTriggeredGenerate.current = triggerGenerateCount;
    void generateVariants({ autoInsertFirst: existingLines.length === 0 });
  }, [triggerGenerateCount, canGenerate, existingLines.length, isGenerating]);

  return (
    <div
      id="generate-dialogue-panel"
      className="flex flex-col gap-4 rounded-md border border-border/60 p-4"
    >
      <div className="flex items-center gap-2">
        <Sparkles className="size-4 text-muted-foreground" />
        <Label>Generate dialogue with Gemini</Label>
      </div>

      <GrammarPointPicker
        label="Target grammar"
        description="Pick the grammar points this dialogue should practice."
        value={selectedGrammarPointIds}
        onChange={setSelectedGrammarPointIds}
      />

      <DifficultyLevelPicker value={difficulty} onChange={setDifficulty} />

      <FormalityLevelPicker value={formality} onChange={setFormality} />

      {setting.trim() ? (
        <div className="rounded-md bg-muted/40 p-3">
          <Label className="text-xs">Using setting as the brief</Label>
          <p className="mt-1 text-sm text-muted-foreground">{setting.trim()}</p>
        </div>
      ) : (
        <Textarea
          rows={3}
          value={extraInstructions}
          onChange={(event) => setExtraInstructions(event.target.value)}
          placeholder='Describe the conversation, e.g. "A student asks the librarian where to find quiet study desks."'
        />
      )}

      {setting.trim() ? (
        <div className="flex flex-col gap-2">
          <Label className="text-xs">Optional extra instructions</Label>
          <Textarea
            rows={2}
            value={extraInstructions}
            onChange={(event) => setExtraInstructions(event.target.value)}
            placeholder="Add tone, constraints, or details beyond the setting."
          />
        </div>
      ) : null}

      <div className="grid grid-cols-2 gap-3">
        <div className="flex flex-col gap-2">
          <Label className="text-xs">Speaker 1</Label>
          <Input
            value={speaker1}
            onChange={(event) => setSpeaker1(event.target.value)}
            placeholder="Student"
          />
        </div>
        <div className="flex flex-col gap-2">
          <Label className="text-xs">Speaker 2</Label>
          <Input
            value={speaker2}
            onChange={(event) => setSpeaker2(event.target.value)}
            placeholder="Librarian"
          />
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-3">
        <Tabs
          value={mode}
          onValueChange={(value) => {
            if (value) setMode(value as "replace" | "append");
          }}
        >
          <TabsList>
            <TabsTrigger value="replace" className="text-xs">
              Replace lines
            </TabsTrigger>
            <TabsTrigger
              value="append"
              className="text-xs"
              disabled={existingLines.length === 0}
            >
              Append to lines
            </TabsTrigger>
          </TabsList>
        </Tabs>
        <Button
          size="sm"
          onClick={() => void generateVariants()}
          disabled={isGenerating || !canGenerate}
        >
          {isGenerating
            ? "Generating options…"
            : `Generate ${VARIANT_COUNT} options`}
        </Button>
        {variants.length > 0 ? (
          <Button
            size="sm"
            variant="ghost"
            onClick={() => setVariants([])}
            disabled={isGenerating}
          >
            Clear options
          </Button>
        ) : null}
      </div>

      {!canGenerate ? (
        <p className="text-xs text-muted-foreground">
          Add a setting on Overview or describe the conversation above.
        </p>
      ) : null}

      {variants.length > 0 ? (
        <div className="grid gap-3 lg:grid-cols-3">
          {variants.map((variant) => (
            <Card key={variant.index} size="sm">
              <CardHeader>
                <CardTitle>Option {variant.index + 1}</CardTitle>
              </CardHeader>
              <CardContent className="flex flex-col gap-2">
                {variant.loading ? (
                  <p className="text-sm text-muted-foreground">Generating…</p>
                ) : null}
                {variant.error ? (
                  <p className="text-sm text-destructive">{variant.error}</p>
                ) : null}
                {variant.generated ? (
                  <>
                    {variant.generated.setting ? (
                      <p className="text-xs text-muted-foreground">
                        {variant.generated.setting}
                      </p>
                    ) : null}
                    {mode === "replace" && existingLines.length > 0 ? (
                      <Button
                        size="sm"
                        variant="ghost"
                        className="w-fit"
                        onClick={() =>
                          setVariants((prev) =>
                            prev.map((v) =>
                              v.index === variant.index
                                ? { ...v, compare: !v.compare }
                                : v
                            )
                          )
                        }
                      >
                        {variant.compare
                          ? "Hide current lines"
                          : "Compare with current"}
                      </Button>
                    ) : null}
                    {variant.compare ? (
                      <div className="flex max-h-40 flex-col gap-1 overflow-y-auto rounded-md bg-muted/40 p-2">
                        <p className="text-xs font-medium text-muted-foreground">
                          Current lines (will be replaced)
                        </p>
                        {existingLines.map((line, lineIndex) => (
                          <div
                            key={lineIndex}
                            className="text-xs text-muted-foreground"
                          >
                            {isSpokenLine(line) ? (
                              <>
                                <span className="font-medium">{line.speaker}:</span>{" "}
                                {line.japanese}
                              </>
                            ) : (
                              <span className="italic">
                                {formatDialogueTranscriptLine(line)}
                              </span>
                            )}
                          </div>
                        ))}
                      </div>
                    ) : null}
                    <div className="flex max-h-64 flex-col gap-2 overflow-y-auto">
                      {variant.generated.lines.map((line, lineIndex) => (
                        <div key={lineIndex} className="text-sm">
                          <span className="font-medium">{line.speaker}:</span>{" "}
                          {line.japanese}
                          <div className="text-xs text-muted-foreground">
                            {line.romaji} — {line.english}
                          </div>
                          {line.grammarPointIDs &&
                          line.grammarPointIDs.length > 0 ? (
                            <div className="text-xs text-muted-foreground">
                              Grammar: {line.grammarPointIDs.join(", ")}
                            </div>
                          ) : null}
                        </div>
                      ))}
                    </div>
                  </>
                ) : null}
              </CardContent>
              {variant.generated ? (
                <CardFooter>
                  <Button
                    size="sm"
                    className="w-full"
                    onClick={() => {
                      insertGenerated(variant.generated!);
                      setVariants([]);
                    }}
                  >
                    {mode === "replace" && existingLines.length > 0
                      ? "Replace current lines"
                      : "Use this"}
                  </Button>
                </CardFooter>
              ) : null}
            </Card>
          ))}
        </div>
      ) : null}
    </div>
  );
}
