import type { CatalogKanji, CatalogShowcaseItem, ShowcaseKind } from "./types";

type CompoundTuple = [expression: string, reading: string, gloss: string, kind?: ShowcaseKind];

function item(
  expression: string,
  reading: string,
  gloss: string,
  kind: ShowcaseKind = "compound"
): CatalogShowcaseItem {
  return { expression, reading, gloss, kind };
}

function k(
  character: string,
  meanings: string[],
  onReadings: string[],
  kunReadings: string[],
  compounds: CompoundTuple[]
): CatalogKanji {
  const parsed = compounds.map(([expression, reading, gloss, kind]) =>
    item(expression, reading, gloss, kind ?? "compound")
  );
  return {
    character,
    meanings,
    onReadings,
    kunReadings,
    compounds: parsed.filter((row) => row.kind === "compound"),
    verbs: parsed.filter((row) => row.kind === "verb"),
  };
}

export const CATALOG_KANJI: CatalogKanji[] = [
  k("一", ["one"], ["イチ", "イツ"], ["ひと"], [["一人", "ひとり", "one person"], ["一日", "いちにち", "one day"], ["一つ", "ひとつ", "one (thing)"]]),
  k("右", ["right"], ["ウ", "ユウ"], ["みぎ"], [["右手", "みぎて", "right hand"], ["左右", "さゆう", "left and right"], ["右側", "みぎがわ", "right side"]]),
  k("雨", ["rain"], ["ウ"], ["あめ", "あま"], [["大雨", "おおあめ", "heavy rain"], ["雨水", "あまみず", "rainwater"], ["雨天", "うてん", "rainy weather"]]),
  k("円", ["circle", "yen"], ["エン"], ["まる"], [["円い", "まるい", "round", "verb"], ["円周", "えんしゅう", "circumference"], ["円高", "えんだか", "strong yen"]]),
  k("王", ["king"], ["オウ"], [], [["王子", "おうじ", "prince"], ["王国", "おうこく", "kingdom"], ["女王", "じょおう", "queen"]]),
  k("音", ["sound"], ["オン", "イン"], ["おと", "ね"], [["音楽", "おんがく", "music"], ["本音", "ほんね", "true feelings"], ["発音", "はつおん", "pronunciation"]]),
  k("下", ["below", "down", "under"], ["カ", "ゲ"], ["した", "しも", "もと"], [["下手", "へた", "unskillful"], ["下着", "したぎ", "underwear"], ["下車", "げしゃ", "getting off"]]),
  k("火", ["fire"], ["カ"], ["ひ"], [["火山", "かざん", "volcano"], ["花火", "はなび", "fireworks"], ["火曜日", "かようび", "Tuesday"]]),
  k("花", ["flower"], ["カ"], ["はな"], [["花火", "はなび", "fireworks"], ["花見", "はなみ", "cherry-blossom viewing"], ["生花", "いけばな", "flower arrangement"]]),
  k("貝", ["shellfish"], ["バイ"], ["かい"], [["貝殻", "かいがら", "seashell"], ["貝類", "かいるい", "shellfish"], ["貝合わせ", "かいあわせ", "shell matching"]]),
  k("学", ["study", "learning"], ["ガク"], ["まな"], [["学校", "がっこう", "school"], ["学生", "がくせい", "student"], ["入学", "にゅうがく", "entering school"], ["学ぶ", "まなぶ", "to learn", "verb"]]),
  k("気", ["spirit", "mind", "air"], ["キ", "ケ"], [], [["天気", "てんき", "weather"], ["元気", "げんき", "healthy / energetic"], ["気持ち", "きもち", "feeling"]]),
  k("九", ["nine"], ["キュウ", "ク"], ["ここの"], [["九日", "ここのか", "ninth day"], ["九州", "きゅうしゅう", "Kyushu"], ["九つ", "ここのつ", "nine (things)"]]),
  k("休", ["rest"], ["キュウ"], ["やす"], [["休日", "きゅうじつ", "holiday"], ["休校", "きゅうこう", "school closed"], ["休み", "やすみ", "break / day off"], ["休む", "やすむ", "to rest", "verb"]]),
  k("玉", ["ball", "jewel"], ["ギョク"], ["たま"], [["目玉", "めだま", "eyeball"], ["玉子", "たまご", "egg"], ["十円玉", "じゅうえんだま", "10-yen coin"]]),
  k("金", ["gold", "money", "Friday"], ["キン", "コン"], ["かね", "かな"], [["金曜日", "きんようび", "Friday"], ["お金", "おかね", "money"], ["金魚", "きんぎょ", "goldfish"]]),
  k("空", ["sky", "empty"], ["クウ"], ["そら", "あ", "から"], [["空港", "くうこう", "airport"], ["空気", "くうき", "air"], ["青空", "あおぞら", "blue sky"], ["空く", "あく", "to become empty", "verb"]]),
  k("月", ["moon", "month"], ["ゲツ", "ガツ"], ["つき"], [["月曜日", "げつようび", "Monday"], ["今月", "こんげつ", "this month"], ["月光", "げっこう", "moonlight"]]),
  k("犬", ["dog"], ["ケン"], ["いぬ"], [["子犬", "こいぬ", "puppy"], ["番犬", "ばんけん", "watchdog"], ["犬小屋", "いぬごや", "doghouse"]]),
  k("見", ["see", "look"], ["ケン"], ["み"], [["見物", "けんぶつ", "sightseeing"], ["意見", "いけん", "opinion"], ["花見", "はなみ", "cherry-blossom viewing"], ["見る", "みる", "to see", "verb"]]),
  k("五", ["five"], ["ゴ"], ["いつ"], [["五日", "いつか", "fifth day"], ["五月", "ごがつ", "May"], ["五つ", "いつつ", "five (things)"]]),
  k("口", ["mouth", "opening"], ["コウ", "ク"], ["くち"], [["入口", "いりぐち", "entrance"], ["出口", "でぐち", "exit"], ["人口", "じんこう", "population"]]),
  k("校", ["school"], ["コウ"], [], [["学校", "がっこう", "school"], ["校長", "こうちょう", "principal"], ["校庭", "こうてい", "schoolyard"]]),
  k("左", ["left"], ["サ"], ["ひだり"], [["左手", "ひだりて", "left hand"], ["左右", "さゆう", "left and right"], ["左側", "ひだりがわ", "left side"]]),
  k("三", ["three"], ["サン"], ["み"], [["三日", "みっか", "third day"], ["三月", "さんがつ", "March"], ["三人", "さんにん", "three people"]]),
  k("山", ["mountain"], ["サン"], ["やま"], [["火山", "かざん", "volcano"], ["山田", "やまだ", "Yamada"], ["山道", "やまみち", "mountain path"]]),
  k("子", ["child"], ["シ", "ス"], ["こ"], [["子供", "こども", "child"], ["女子", "じょし", "girl / woman"], ["帽子", "ぼうし", "hat"]]),
  k("四", ["four"], ["シ"], ["よん", "よ"], [["四日", "よっか", "fourth day"], ["四月", "しがつ", "April"], ["四季", "しき", "four seasons"]]),
  k("糸", ["thread"], ["シ"], ["いと"], [["毛糸", "けいと", "wool yarn"], ["糸口", "いとぐち", "clue"], ["蚕糸", "さんし", "silk thread"]]),
  k("字", ["character", "letter"], ["ジ"], ["あざ"], [["文字", "もじ", "letter / character"], ["数字", "すうじ", "numeral"], ["名字", "みょうじ", "family name"]]),
  k("耳", ["ear"], ["ジ"], ["みみ"], [["耳鼻", "じび", "ear and nose"], ["耳元", "みみもと", "close to the ear"], ["初耳", "はつみみ", "news to me"]]),
  k("七", ["seven"], ["シチ"], ["なな"], [["七日", "なのか", "seventh day"], ["七月", "しちがつ", "July"], ["七つ", "ななつ", "seven (things)"]]),
  k("車", ["car", "vehicle"], ["シャ"], ["くるま"], [["電車", "でんしゃ", "train"], ["自転車", "じてんしゃ", "bicycle"], ["自動車", "じどうしゃ", "automobile"]]),
  k("手", ["hand"], ["シュ"], ["て"], [["手紙", "てがみ", "letter"], ["上手", "じょうず", "skillful"], ["下手", "へた", "unskillful"]]),
  k("十", ["ten"], ["ジュウ"], ["とお"], [["十日", "とおか", "tenth day"], ["十月", "じゅうがつ", "October"], ["十分", "じゅうぶん", "enough"]]),
  k("出", ["exit", "leave"], ["シュツ"], ["で", "だ"], [["出口", "でぐち", "exit"], ["外出", "がいしゅつ", "going out"], ["思い出", "おもいで", "memory"], ["出る", "でる", "to leave / appear", "verb"]]),
  k("女", ["woman", "female"], ["ジョ", "ニョ"], ["おんな"], [["女子", "じょし", "girl / woman"], ["彼女", "かのじょ", "she / girlfriend"], ["女の子", "おんなのこ", "girl"]]),
  k("小", ["small"], ["ショウ"], ["ちい", "こ", "お"], [["小学校", "しょうがっこう", "elementary school"], ["小説", "しょうせつ", "novel"], ["小川", "おがわ", "brook"]]),
  k("上", ["above", "up"], ["ジョウ"], ["うえ", "あ"], [["上手", "じょうず", "skillful"], ["以上", "いじょう", "more than"], ["上着", "うわぎ", "jacket"], ["上がる", "あがる", "to go up", "verb"]]),
  k("森", ["forest"], ["シン"], ["もり"], [["森林", "しんりん", "forest"], ["森閑", "しんかん", "silence"], ["森々", "しんしん", "densely wooded"]]),
  k("人", ["person"], ["ジン", "ニン"], ["ひと"], [["日本人", "にほんじん", "Japanese person"], ["人口", "じんこう", "population"], ["一人", "ひとり", "one person"]]),
  k("水", ["water"], ["スイ"], ["みず"], [["水曜日", "すいようび", "Wednesday"], ["水分", "すいぶん", "moisture"], ["水泳", "すいえい", "swimming"]]),
  k("生", ["life", "birth", "raw"], ["セイ", "ショウ"], ["い", "う", "なま"], [["学生", "がくせい", "student"], ["先生", "せんせい", "teacher"], ["生活", "せいかつ", "life / living"], ["生きる", "いきる", "to live", "verb"]]),
  k("青", ["blue", "green"], ["セイ", "ショウ"], ["あお"], [["青空", "あおぞら", "blue sky"], ["青春", "せいしゅん", "youth"], ["青信号", "あおしんごう", "green light"]]),
  k("夕", ["evening"], ["セキ"], ["ゆう"], [["夕方", "ゆうがた", "evening"], ["夕食", "ゆうしょく", "dinner"], ["夕日", "ゆうひ", "setting sun"]]),
  k("石", ["stone"], ["セキ", "シャク"], ["いし"], [["化石", "かせき", "fossil"], ["石油", "せきゆ", "petroleum"], ["宝石", "ほうせき", "jewel"]]),
  k("赤", ["red"], ["セキ"], ["あか"], [["赤字", "あかじ", "deficit"], ["赤信号", "あかしんごう", "red light"], ["赤ちゃん", "あかちゃん", "baby"]]),
  k("千", ["thousand"], ["セン"], ["ち"], [["千円", "せんえん", "1,000 yen"], ["千葉", "ちば", "Chiba"], ["千里", "せんり", "a thousand ri"]]),
  k("川", ["river"], ["セン"], ["かわ"], [["川口", "かわぐち", "river mouth"], ["小川", "おがわ", "brook"], ["川辺", "かわべ", "riverside"]]),
  k("先", ["ahead", "previous", "the tip"], ["セン"], ["さき"], [["先生", "せんせい", "teacher"], ["先週", "せんしゅう", "last week"], ["先日", "せんじつ", "the other day"]]),
  k("早", ["early", "fast"], ["ソウ"], ["はや"], [["早速", "さっそく", "immediately"], ["早朝", "そうちょう", "early morning"], ["早口", "はやくち", "fast talk"], ["早い", "はやい", "early / fast", "verb"]]),
  k("草", ["grass"], ["ソウ"], ["くさ"], [["草花", "くさばな", "flowering plant"], ["雑草", "ざっそう", "weed"], ["草案", "そうあん", "draft"]]),
  k("足", ["foot", "leg", "sufficient"], ["ソク"], ["あし", "た"], [["足音", "あしおと", "footsteps"], ["遠足", "えんそく", "excursion"], ["足りる", "たりる", "to be enough", "verb"]]),
  k("村", ["village"], ["ソン"], ["むら"], [["村人", "むらびと", "villager"], ["山村", "さんそん", "mountain village"], ["農村", "のうそん", "farming village"]]),
  k("大", ["big", "large"], ["ダイ", "タイ"], ["おお"], [["大学", "だいがく", "university"], ["大人", "おとな", "adult"], ["大切", "たいせつ", "important"]]),
  k("男", ["man", "male"], ["ダン", "ナン"], ["おとこ"], [["男子", "だんし", "boy / man"], ["長男", "ちょうなん", "eldest son"], ["男の子", "おとこのこ", "boy"]]),
  k("竹", ["bamboo"], ["チク"], ["たけ"], [["竹林", "ちくりん", "bamboo grove"], ["竹馬", "たけうま", "stilts"], ["爆竹", "ばくちく", "firecracker"]]),
  k("中", ["middle", "inside", "China"], ["チュウ"], ["なか"], [["中国", "ちゅうごく", "China"], ["中学", "ちゅうがく", "junior high"], ["一日中", "いちにちじゅう", "all day"]]),
  k("虫", ["insect"], ["チュウ"], ["むし"], [["昆虫", "こんちゅう", "insect"], ["虫歯", "むしば", "cavity"], ["弱虫", "よわむし", "coward"]]),
  k("町", ["town"], ["チョウ"], ["まち"], [["町中", "まちなか", "downtown"], ["商店", "しょうてん", "shop"], ["町内", "ちょうない", "neighborhood"]]),
  k("天", ["heaven", "sky"], ["テン"], ["あま", "あめ"], [["天気", "てんき", "weather"], ["天井", "てんじょう", "ceiling"], ["天才", "てんさい", "genius"]]),
  k("田", ["rice field"], ["デン"], ["た"], [["田中", "たなか", "Tanaka"], ["水田", "すいでん", "paddy"], ["田んぼ", "たんぼ", "rice field"]]),
  k("土", ["soil", "earth", "Saturday"], ["ド", "ト"], ["つち"], [["土曜日", "どようび", "Saturday"], ["土地", "とち", "land"], ["土産", "みやげ", "souvenir"]]),
  k("二", ["two"], ["ニ"], ["ふた"], [["二人", "ふたり", "two people"], ["二月", "にがつ", "February"], ["二つ", "ふたつ", "two (things)"]]),
  k("日", ["day", "sun", "Japan"], ["ニチ", "ジツ"], ["ひ", "か"], [["日本", "にほん", "Japan"], ["日曜日", "にちようび", "Sunday"], ["毎日", "まいにち", "every day"]]),
  k("入", ["enter"], ["ニュウ"], ["はい", "い"], [["入学", "にゅうがく", "entering school"], ["入口", "いりぐち", "entrance"], ["入力", "にゅうりょく", "input"], ["入る", "はいる", "to enter", "verb"]]),
  k("年", ["year"], ["ネン"], ["とし"], [["今年", "ことし", "this year"], ["来年", "らいねん", "next year"], ["年中", "ねんじゅう", "all year"]]),
  k("白", ["white"], ["ハク", "ビャク"], ["しろ"], [["白鳥", "はくちょう", "swan"], ["空白", "くうはく", "blank"], ["白い", "しろい", "white", "verb"]]),
  k("八", ["eight"], ["ハチ"], ["や"], [["八日", "ようか", "eighth day"], ["八月", "はちがつ", "August"], ["八つ", "やっつ", "eight (things)"]]),
  k("百", ["hundred"], ["ヒャク"], ["もも"], [["百円", "ひゃくえん", "100 yen"], ["百年", "ひゃくねん", "a hundred years"], ["百科", "ひゃっか", "encyclopedia"]]),
  k("文", ["writing", "sentence", "literature"], ["ブン", "モン"], ["ふみ"], [["文字", "もじ", "letter / character"], ["作文", "さくぶん", "composition"], ["文化", "ぶんか", "culture"]]),
  k("木", ["tree", "wood"], ["ボク", "モク"], ["き"], [["木曜日", "もくようび", "Thursday"], ["木村", "きむら", "Kimura"], ["大木", "たいぼく", "big tree"]]),
  k("本", ["book", "origin", "true"], ["ホン"], ["もと"], [["日本", "にほん", "Japan"], ["本日", "ほんじつ", "today"], ["本音", "ほんね", "true feelings"]]),
  k("名", ["name", "famous"], ["メイ", "ミョウ"], ["な"], [["名前", "なまえ", "name"], ["有名", "ゆうめい", "famous"], ["名刺", "めいし", "business card"]]),
  k("目", ["eye"], ["モク", "ボク"], ["め"], [["目的", "もくてき", "purpose"], ["注目", "ちゅうもく", "attention"], ["一目", "ひとめ", "a glance"]]),
  k("立", ["stand"], ["リツ", "リュウ"], ["た"], [["国立", "こくりつ", "national"], ["立場", "たちば", "standpoint"], ["独立", "どくりつ", "independence"], ["立つ", "たつ", "to stand", "verb"]]),
  k("力", ["power", "strength"], ["リョク", "リキ"], ["ちから"], [["全力", "ぜんりょく", "full power"], ["入力", "にゅうりょく", "input"], ["出力", "しゅつりょく", "output"]]),
  k("林", ["woods"], ["リン"], ["はやし"], [["森林", "しんりん", "forest"], ["林道", "りんどう", "forest road"], ["竹林", "ちくりん", "bamboo grove"]]),
  k("六", ["six"], ["ロク"], ["む"], [["六日", "むいか", "sixth day"], ["六月", "ろくがつ", "June"], ["六つ", "むっつ", "six (things)"]]),
];

export const CATALOG_WORD_SEEDS: Array<{
  expression: string;
  reading: string;
  gloss: string;
  glossOptions?: string[];
}> = [
  { expression: "日本", reading: "にほん", gloss: "Japan" },
  { expression: "人口", reading: "じんこう", gloss: "population" },
  { expression: "火山", reading: "かざん", gloss: "volcano" },
  { expression: "大人", reading: "おとな", gloss: "adult" },
  { expression: "女子", reading: "じょし", gloss: "girl; woman", glossOptions: ["girl", "woman", "female student"] },
  { expression: "男子", reading: "だんし", gloss: "boy; man", glossOptions: ["boy", "man", "male student"] },
  { expression: "学校", reading: "がっこう", gloss: "school" },
  { expression: "学生", reading: "がくせい", gloss: "student" },
  { expression: "入学", reading: "にゅうがく", gloss: "entering school", glossOptions: ["enrollment", "entering school"] },
  { expression: "休日", reading: "きゅうじつ", gloss: "holiday" },
  { expression: "花火", reading: "はなび", gloss: "fireworks" },
  { expression: "左右", reading: "さゆう", gloss: "left and right" },
  { expression: "上下", reading: "じょうげ", gloss: "up and down" },
  { expression: "大小", reading: "だいしょう", gloss: "size; large and small" },
  { expression: "青空", reading: "あおぞら", gloss: "blue sky" },
  { expression: "手足", reading: "てあし", gloss: "hands and feet" },
  { expression: "森林", reading: "しんりん", gloss: "forest" },
  { expression: "出口", reading: "でぐち", gloss: "exit" },
  { expression: "入口", reading: "いりぐち", gloss: "entrance" },
  { expression: "空中", reading: "くうちゅう", gloss: "in the air; sky" },
  { expression: "天気", reading: "てんき", gloss: "weather" },
  { expression: "花見", reading: "はなみ", gloss: "cherry-blossom viewing" },
  { expression: "月見", reading: "つきみ", gloss: "moon viewing" },
  { expression: "王子", reading: "おうじ", gloss: "prince" },
  { expression: "草花", reading: "くさばな", gloss: "flowering plant" },
  { expression: "赤子", reading: "あかご", gloss: "baby" },
  { expression: "土日", reading: "どにち", gloss: "weekend" },
  { expression: "木村", reading: "きむら", gloss: "Kimura" },
  { expression: "夕日", reading: "ゆうひ", gloss: "setting sun" },
  { expression: "町中", reading: "まちなか", gloss: "in town" },
  { expression: "糸口", reading: "いとぐち", gloss: "clue" },
  { expression: "本日", reading: "ほんじつ", gloss: "today" },
  { expression: "先日", reading: "せんじつ", gloss: "the other day" },
  { expression: "年生", reading: "ねんせい", gloss: "year student; grader" },
  { expression: "中学", reading: "ちゅうがく", gloss: "junior high" },
  { expression: "小学", reading: "しょうがく", gloss: "elementary school" },
  { expression: "大金", reading: "たいきん", gloss: "large sum of money" },
  { expression: "山水", reading: "さんすい", gloss: "landscape; mountains and water" },
  { expression: "川口", reading: "かわぐち", gloss: "river mouth" },
  { expression: "大雨", reading: "おおあめ", gloss: "heavy rain" },
  { expression: "火力", reading: "かりょく", gloss: "thermal power; firepower" },
  { expression: "水力", reading: "すいりょく", gloss: "water power" },
  { expression: "入力", reading: "にゅうりょく", gloss: "input" },
  { expression: "出力", reading: "しゅつりょく", gloss: "output" },
  { expression: "文字", reading: "もじ", gloss: "letter; character" },
  { expression: "本文", reading: "ほんぶん", gloss: "main text" },
  { expression: "名目", reading: "めいもく", gloss: "pretext; in name" },
  { expression: "人目", reading: "ひとめ", gloss: "public eye" },
  { expression: "足下", reading: "あしもと", gloss: "at one's feet" },
  { expression: "車中", reading: "しゃちゅう", gloss: "in a vehicle" },
  { expression: "小学校", reading: "しょうがっこう", gloss: "elementary school" },
  { expression: "中学校", reading: "ちゅうがっこう", gloss: "junior high school" },
  { expression: "日本人", reading: "にほんじん", gloss: "Japanese person" },
  { expression: "一年生", reading: "いちねんせい", gloss: "first-year student" },
  { expression: "二年生", reading: "にねんせい", gloss: "second-year student" },
  { expression: "大学生", reading: "だいがくせい", gloss: "university student" },
  { expression: "女学生", reading: "じょがくせい", gloss: "schoolgirl" },
  { expression: "竹林", reading: "ちくりん", gloss: "bamboo grove" },
  { expression: "火山口", reading: "かざんこう", gloss: "crater" },
  { expression: "右手", reading: "みぎて", gloss: "right hand" },
];
